### Registro de usuario
POST http://localhost:8000/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### Inicio de sesión
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}

### Crear proyecto
POST http://localhost:8000/projects/create
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTc0NDc1NTk0OCwiZXhwIjoxNzQ0NzU5NTQ4LCJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifX0.17fQct4rNWIFMIaToMAcESZeXirqNo7TDPliMflNOQs
Content-Type: application/json

{
  "title": "Nuevo Proyecto",
  "description": "Descripción del proyecto",
  "start_date": "2023-10-01",
  "delivery_date": "2023-12-01",
  "state": "PENDING",
  "user_id": "2"
}

### Listar proyectos
GET http://localhost:8000/projects
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTc0NDc1NzQyNywiZXhwIjoxNzQ0NzYxMDI3LCJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifX0.8Dh88RYNzcjHY60ULjo-3qW80YgEc6uH898jpOC4ZVc

### Obtener proyecto por ID
GET http://localhost:8000/projects/get/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTc0NDc1NzQyNywiZXhwIjoxNzQ0NzYxMDI3LCJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifX0.8Dh88RYNzcjHY60ULjo-3qW80YgEc6uH898jpOC4ZVc

### Actualizar proyecto
PUT http://localhost:8000/projects/update/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTc0NDc1NzQyNywiZXhwIjoxNzQ0NzYxMDI3LCJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifX0.8Dh88RYNzcjHY60ULjo-3qW80YgEc6uH898jpOC4ZVc
Content-Type: application/json

{
  "title": "Proyecto Actualizado",
  "description": "Descripción actualizada",
  "start_date": "2023-10-01",
  "delivery_date": "2023-12-15",
  "state": "PENDING"
}

### Eliminar proyecto
DELETE http://localhost:8000/projects/delete/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCIsImlhdCI6MTc0NDc1NzQyNywiZXhwIjoxNzQ0NzYxMDI3LCJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20ifX0.8Dh88RYNzcjHY60ULjo-3qW80YgEc6uH898jpOC4ZVc